#!/usr/bin/env python3
"""Generate deterministic notices from dependencies actually shipped at runtime."""

from __future__ import annotations

import json
import os
import pathlib
import subprocess
from collections import defaultdict, deque

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "THIRD_PARTY_NOTICES.txt"
LICENSE_PATTERNS = ("LICENSE*", "COPYING*", "NOTICE*")
GOOS_TARGETS = ("linux", "darwin", "windows")


def json_stream(text: str):
    decoder = json.JSONDecoder()
    position = 0
    while position < len(text):
        while position < len(text) and text[position].isspace():
            position += 1
        if position >= len(text):
            return
        value, position = decoder.raw_decode(text, position)
        yield value


def license_documents(directory: pathlib.Path):
    paths = []
    for pattern in LICENSE_PATTERNS:
        paths.extend(path for path in directory.glob(pattern) if path.is_file())
    for path in sorted(set(paths), key=lambda item: item.name):
        text = path.read_text(encoding="utf-8", errors="replace").strip()
        if text:
            yield path.name, text


def go_components():
    modules = {}
    for goos in GOOS_TARGETS:
        raw = subprocess.check_output(
            ["go", "list", "-deps", "-json", "./cmd/zeno-agent"],
            cwd=ROOT,
            text=True,
            env={**os.environ, "GOOS": goos, "GOARCH": "amd64", "CGO_ENABLED": "0"},
        )
        for package in json_stream(raw):
            module = package.get("Module")
            if not module or module.get("Main") or not module.get("Dir"):
                continue
            modules[module["Path"]] = (module.get("Version", ""), pathlib.Path(module["Dir"]))
    for name, (version, directory) in sorted(modules.items()):
        documents = list(license_documents(directory))
        if not documents:
            raise SystemExit(f"missing Go module license document: {name}@{version}")
        for filename, text in documents:
            yield f"Go module {name}@{version} ({filename})", text


def npm_components():
    lock_path = ROOT / "web" / "package-lock.json"
    if not lock_path.exists():
        return
    packages = json.loads(lock_path.read_text())["packages"]
    root = packages[""]
    queue = deque(root.get("dependencies", {}).keys())
    seen = set()
    while queue:
        name = queue.popleft()
        key = f"node_modules/{name}"
        if key in seen:
            continue
        seen.add(key)
        metadata = packages.get(key)
        if metadata is None:
            raise SystemExit(f"runtime npm package missing from lock: {name}")
        queue.extend(metadata.get("dependencies", {}).keys())
    for key in sorted(seen):
        metadata = packages[key]
        directory = ROOT / "web" / key
        documents = list(license_documents(directory))
        if not documents:
            raise SystemExit(f"missing npm package license document: {key}")
        name = key.removeprefix("node_modules/")
        for filename, text in documents:
            yield f"npm package {name}@{metadata.get('version', '')} ({filename})", text


def main():
    grouped = defaultdict(list)
    for label, text in [*go_components(), *npm_components()]:
        grouped[text].append(label)
    sections = [
        "Zeno third-party notices",
        "Generated by scripts/generate-third-party-notices.py from runtime dependencies.",
        "Do not edit manually.",
    ]
    for text, labels in sorted(grouped.items(), key=lambda item: tuple(sorted(item[1]))):
        sections.extend(["", "=" * 78, *sorted(labels), "-" * 78, text])
    OUTPUT.write_text("\n".join(sections).rstrip() + "\n")


if __name__ == "__main__":
    main()
